#!/bin/bash
#
#instrument files
#https://github.com/visionmedia/node-jscoverage
#node-jscoverage lib lib-cov
#TODO

#dox --title JSONForm lib/jsonform.js > docs/index.html

#https://github.com/dsimard/ready.js
readyjs ready.conf.js

#execute tests
node runspecs.js